#!/usr/bin/env python
import sys
from pathlib import Path
import os

GMC_DIR = Path(__file__).parents[1]
SRC_DIR = GMC_DIR / "src"
for i in SRC_DIR.glob('**/*'):
    if i.is_dir() and i.name != "__pycache__":
        sys.path.append(str(i))
             
os.environ['GMC_DIR'] = str(GMC_DIR)

# sys.path.append('../src/atoms')
# sys.path.append('../src/debug')
# sys.path.append('../src/euro')
# sys.path.append('../src/grpc')
# sys.path.append('../src/gui')
# sys.path.append('../src/managers')
# sys.path.append('../src/widgets')
# sys.path.append('../src/widgets/atoms')
# sys.path.append('../src/widgets/tree')

from GUI import *

# TODO: ENSURE BALANCE CAN'T HAVE ABSURDS VALUES (eg: 16.33333...)       [OK Money class + string]
# TODO: FIX MULTI-USER PANEL
# TODO: UNIFY KEY NAME BITWEEN THE SERVER AND THE CLIENT                 [OK GRPC]
# TODO: MAKE AUTOMATIC GRAPH
# TODO: FIND A EASIER WAY TO HANDLE TREEMODELS AND STUFF...              [OK QATOMS]
# TODO: ADD WARNING WHEN ADD HUGE AMOUNT ON CARDS
# TODO: HANDLE TRANSLATION
# TODO: ADD A TOOLBAR STATUS SINGLETON HANDLER                          [OK VIA QCONNECTOR]
# TODO: HANDLE CARD READER PLUG/UNPLUG                                  [OK]
# TODO: ADD TRADUCTION

if __name__ == "__main__":
    app = QApplication.instance()
    if not app:
        app = QApplication(sys.argv)
    # translation
    locale = QLocale.system().name()
    qtTranslator = QTranslator()
    print(QLibraryInfo.location(QLibraryInfo.TranslationsPath))
    frenchLocale = QLocale(QLocale.French, QLocale.France)
    if qtTranslator.load(locale, "qt_" + locale):
        print("qtTranslator installed")
        app.installTranslator(qtTranslator)

    MainWindow = QMainMenu()
    VirtualCard = QVirtualCard()

    # la fenêtre est rendue visible
    #    MainWindow.showMaximized()
    MainWindow.show()
    # VirtualCard.show()
    app.exec_()
